// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCredits(arg1) {
  return window['go']['main']['App']['AddCredits'](arg1);
}

export function AddVocabulary(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddVocabulary'](arg1, arg2, arg3);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CompleteSetup(arg1, arg2) {
  return window['go']['main']['App']['CompleteSetup'](arg1, arg2);
}

export function CompleteTutorial() {
  return window['go']['main']['App']['CompleteTutorial']();
}

export function DeleteLog(arg1) {
  return window['go']['main']['App']['DeleteLog'](arg1);
}

export function DeleteVocabulary(arg1) {
  return window['go']['main']['App']['DeleteVocabulary'](arg1);
}

export function DownloadUpdate(arg1, arg2) {
  return window['go']['main']['App']['DownloadUpdate'](arg1, arg2);
}

export function ExportData() {
  return window['go']['main']['App']['ExportData']();
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConsistencyPhase() {
  return window['go']['main']['App']['GetConsistencyPhase']();
}

export function GetEngressBriefing() {
  return window['go']['main']['App']['GetEngressBriefing']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadState() {
  return window['go']['main']['App']['LoadState']();
}

export function LogSession(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['LogSession'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ResetAppData() {
  return window['go']['main']['App']['ResetAppData']();
}

export function SaveState(arg1) {
  return window['go']['main']['App']['SaveState'](arg1);
}

export function SetHUDScratchpadVisible(arg1) {
  return window['go']['main']['App']['SetHUDScratchpadVisible'](arg1);
}

export function SetPauseState(arg1) {
  return window['go']['main']['App']['SetPauseState'](arg1);
}

export function SetSessionCategory(arg1) {
  return window['go']['main']['App']['SetSessionCategory'](arg1);
}

export function SetState(arg1) {
  return window['go']['main']['App']['SetState'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartScheduler() {
  return window['go']['main']['App']['StartScheduler']();
}

export function UpdateLastLogSession(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateLastLogSession'](arg1, arg2, arg3, arg4);
}

export function UpdateNotes(arg1) {
  return window['go']['main']['App']['UpdateNotes'](arg1);
}

export function UpdateProfileName(arg1) {
  return window['go']['main']['App']['UpdateProfileName'](arg1);
}

export function UpdateReminders(arg1, arg2) {
  return window['go']['main']['App']['UpdateReminders'](arg1, arg2);
}

export function UpdateTestDate(arg1) {
  return window['go']['main']['App']['UpdateTestDate'](arg1);
}

export function UpdateTrayTime(arg1) {
  return window['go']['main']['App']['UpdateTrayTime'](arg1);
}
