// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCredits(arg1:number):Promise<void>;

export function AddVocabulary(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CheckUpdate():Promise<main.UpdateInfo>;

export function CompleteSetup(arg1:string,arg2:string):Promise<void>;

export function CompleteTutorial():Promise<void>;

export function DeleteLog(arg1:string):Promise<void>;

export function DeleteVocabulary(arg1:string):Promise<void>;

export function DownloadUpdate(arg1:string,arg2:string):Promise<string>;

export function ExportData():Promise<void>;

export function GetAppState():Promise<main.AppState>;

export function GetAppVersion():Promise<string>;

export function GetConsistencyPhase():Promise<string>;

export function GetEngressBriefing():Promise<string>;

export function GetState():Promise<main.AppState>;

export function Greet(arg1:string):Promise<string>;

export function LoadState():Promise<main.AppState>;

export function LogSession(arg1:string,arg2:string,arg3:number,arg4:string,arg5:number,arg6:string,arg7:string,arg8:string,arg9:string):Promise<void>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function Quit():Promise<void>;

export function ResetAppData():Promise<string>;

export function SaveState(arg1:main.AppState):Promise<void>;

export function SetPauseState(arg1:boolean):Promise<void>;

export function SetSessionCategory(arg1:string):Promise<void>;

export function SetState(arg1:main.AppState):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartScheduler():Promise<void>;

export function UpdateLastLogSession(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function UpdateProfileName(arg1:string):Promise<void>;

export function UpdateReminders(arg1:boolean,arg2:string):Promise<void>;

export function UpdateTestDate(arg1:string):Promise<void>;

export function UpdateTrayTime(arg1:string):Promise<void>;
